### ISSUE TITLE
渲染时就执行倒计时

### ISSUE THREAD

**Issue by liyy131225** [yongqianvip/RNCountDown#4]
1. 没有渲染时就执行倒计时的方法

**Comment by yongqianvip** [comment]
描述清楚些，谢谢

**Comment by liyy131225** [comment]
就是页面渲染就执行，或者可以在生命周期里能用类似ref方式调用点击事件

**Comment by yongqianvip** [comment]
抱歉，我忽略了这种场景，如果你愿意的话，可以拷贝源码到你的工程里，稍作修改以适应你的需求

**Comment by liyy131225** [comment]
可以这样做，不过如果能封装就更好了，类似ref 的方法怎么不能控制执行onpress事件，这样就可以渲染就执行了

**Comment by yongqianvip** [comment]
组件更新（0.1.15）新增一个`executeFunc`
  
    <CountDownButton
          executeFunc={(shouldStartCounting)=>{
                // 组件加载完成后 回吐开始倒计时的function 把这个function绑定到当前对象
                this.shouldStartCounting = shouldStartCounting;
          }}
          timerTitle={'获取验证码'}
          enable={ phoneNum.length > 10 && !codeRequesting }
          onClick={(shouldStartCounting) => {}}
          timerEnd={() => {}}
     />

在引用组件的容器中

    componentDidMount() {
        //随机模拟发送验证码成功或失败  
        const requestSucc = Math.random() > 0.5;
        this.shouldStartCountting && this.shouldStartCountting(requestSucc)
    }

**Comment by liyy131225** [comment]
很棒，有时间试一下，方法写在onpress外，想法不错

**Comment by liyy131225** [comment]
安卓的没问题，不知道IOS的支持吗

**Comment by yongqianvip** [comment]
支持
