### ISSUE TITLE
禁用后的背景颜色能否修改

### ISSUE THREAD

**Issue by asagcs** [yongqianvip/RNCountDown#6]
If the button is not clickable, can the background color be changed

**Comment by yongqianvip** [comment]
const enable = phoneNum.length > 10

<CountDownButton enable style={{backgroundColor: enable ? '#eee' : '#fff'}}/>

这是你想要的吗

**Comment by asagcs** [comment]
> const enable = phoneNum.length > 10
> 
> <CountDownButton enable style={{backgroundColor: enable ? '#eee' : '#fff'}}/>
> 
> 这是你想要的吗
是的，谢谢

**Comment by asagcs** [comment]
@yongqianvip 谢谢

**Comment by asagcs** [comment]
是的，非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yongqianvip"<notifications@github.com&gt;; 
发送时间: 2019年9月24日(星期二) 下午4:55
收件人: "yongqianvip/RNCountDown"<RNCountDown@noreply.github.com&gt;; 
抄送: "え。作怪"<1261167816@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yongqianvip/RNCountDown] 禁用后的背景颜色能否修改 (#6)




const enable = phoneNum.length &gt; 10
 
<CountDownButton enable style={{backgroundColor: enable ? '#eee' : '#fff'}}/&gt;
 
这是你想要的吗

**Comment by yongqianvip** [comment]
不用客气，另外提醒一下，倒计时过程中，按钮也是禁用状态，但是这个时候的按钮背景颜色并不是enable为false时的颜色

**Comment by asagcs** [comment]
嗯嗯&nbsp; 了解了&nbsp;&nbsp; 谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yongqianvip"<notifications@github.com&gt;; 
发送时间: 2019年9月24日(星期二) 下午5:17
收件人: "yongqianvip/RNCountDown"<RNCountDown@noreply.github.com&gt;; 
抄送: "え。作怪"<1261167816@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yongqianvip/RNCountDown] 禁用后的背景颜色能否修改 (#6)




不用客气，另外提醒一下，倒计时过程中，按钮也是禁用状态，但是这个时候的按钮背景颜色并不是enable为false时的颜色
